CREATE TABLE IF NOT EXISTS google_credentials (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    client_id VARCHAR(255) NOT NULL,
    client_secret TEXT NOT NULL,
    redirect_uri VARCHAR(255),
    auth_base_url VARCHAR(255),
    oauth_base_url VARCHAR(255),
    api_base_url VARCHAR(255),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM google_credentials) THEN
        INSERT INTO google_credentials (id, tenant_id, client_id, client_secret, redirect_uri, auth_base_url, oauth_base_url, api_base_url, updated_at, created_at)
        VALUES (1, 1, '', '', 'http://localhost:8080/api/v1/google/callback', 'https://accounts.google.com', 'https://oauth2.googleapis.com', 'https://www.googleapis.com', NOW(), NOW());
    END IF;
END $$;
